apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260624-200214-r5kam3a2exfv-service
spec:
  selector:
    app: enterprise-system-20260624-200214-r5kam3a2exfv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
